{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "\n",
    "\n",
    "test_data = pd.read_csv(\n",
    "    \"../files/input/test_data.csv.zip\",\n",
    "    index_col=False,\n",
    "    compression=\"zip\",\n",
    ")\n",
    "\n",
    "train_data = pd.read_csv(\n",
    "    \"../files/input/train_data.csv.zip\",\n",
    "    index_col=False,\n",
    "    compression=\"zip\",\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',\n",
      "       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',\n",
      "       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',\n",
      "       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6', 'default'],\n",
      "      dtype='object')\n"
     ]
    }
   ],
   "source": [
    "# - Renombre la columna \"default payment next month\" a \"default\".\n",
    "test_data = test_data.rename(columns={'default payment next month': 'default'})\n",
    "train_data = train_data.rename(columns={'default payment next month': 'default'})\n",
    "\n",
    "print(test_data.columns)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "# - Remueva la columna \"ID\".\n",
    "test_data=test_data.drop(columns=['ID'])\n",
    "train_data=train_data.drop(columns=['ID'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "EDUCATION\n",
      "2    9756\n",
      "1    7476\n",
      "3    3396\n",
      "5     187\n",
      "4      98\n",
      "6      40\n",
      "Name: count, dtype: int64\n",
      "MARRIAGE\n",
      "2    11226\n",
      "1     9502\n",
      "3      225\n",
      "Name: count, dtype: int64\n",
      "EDUCATION\n",
      "2    4268\n",
      "1    3105\n",
      "3    1477\n",
      "5      93\n",
      "4      25\n",
      "6      11\n",
      "Name: count, dtype: int64\n",
      "MARRIAGE\n",
      "2    4728\n",
      "1    4153\n",
      "3      98\n",
      "Name: count, dtype: int64\n"
     ]
    }
   ],
   "source": [
    "# - Elimine los registros con informacion no disponible.\n",
    "\n",
    "import numpy as np\n",
    "\n",
    "# Para train_data\n",
    "train_data = train_data.loc[train_data[\"MARRIAGE\"] != 0]\n",
    "train_data = train_data.loc[train_data[\"EDUCATION\"] != 0]\n",
    "print(train_data[\"EDUCATION\"].value_counts())\n",
    "print(train_data[\"MARRIAGE\"].value_counts())\n",
    "\n",
    "# Para test_data (corregido)\n",
    "test_data = test_data.loc[test_data[\"MARRIAGE\"] != 0]\n",
    "test_data = test_data.loc[test_data[\"EDUCATION\"] != 0]\n",
    "print(test_data[\"EDUCATION\"].value_counts())\n",
    "print(test_data[\"MARRIAGE\"].value_counts())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "EDUCATION\n",
      "2    9756\n",
      "1    7476\n",
      "3    3396\n",
      "4     325\n",
      "Name: count, dtype: int64\n",
      "EDUCATION\n",
      "2    4268\n",
      "1    3105\n",
      "3    1477\n",
      "4     129\n",
      "Name: count, dtype: int64\n"
     ]
    }
   ],
   "source": [
    "# - Para la columna EDUCATION, valores > 4 indican niveles superiores\n",
    "test_data['EDUCATION'] = test_data['EDUCATION'].apply(lambda x: 4 if x > 4 else x)\n",
    "train_data['EDUCATION'] = train_data['EDUCATION'].apply(lambda x: 4 if x > 4 else x)\n",
    "\n",
    "print(train_data[\"EDUCATION\"].value_counts())\n",
    "print(test_data[\"EDUCATION\"].value_counts())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Divida los datasets en x_train, y_train, x_test, y_test.\n",
    "x_train=train_data.drop(columns=\"default\")\n",
    "y_train=train_data[\"default\"]\n",
    "\n",
    "\n",
    "x_test=test_data.drop(columns=\"default\")\n",
    "y_test=test_data[\"default\"]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.compose import ColumnTransformer\n",
    "from sklearn.pipeline import Pipeline\n",
    "from sklearn.preprocessing import OneHotEncoder, MinMaxScaler\n",
    "from sklearn.feature_selection import SelectKBest, f_classif\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "\n",
    "# Columnas categóricas\n",
    "categorical_features = [\"SEX\", \"EDUCATION\", \"MARRIAGE\"]\n",
    "\n",
    "# Paso 1: Preprocesar variables categóricas con OneHotEncoder\n",
    "categorical_transformer = OneHotEncoder(drop='first', handle_unknown='ignore')\n",
    "\n",
    "# Paso 2: Combinar el preprocesamiento en un transformador de columnas\n",
    "preprocessor = ColumnTransformer(\n",
    "    transformers=[\n",
    "        ('cat', categorical_transformer, categorical_features)  # Transformación categórica\n",
    "    ],\n",
    "    remainder='passthrough'  # Mantener variables numéricas sin tocar para el siguiente paso\n",
    ")\n",
    "\n",
    "# Paso 3: Crear el pipeline con los pasos en el orden deseado\n",
    "pipeline = Pipeline(steps=[\n",
    "    ('OneHotEncoder', preprocessor),\n",
    "    ('SelectKBest', SelectKBest(score_func=f_classif, k=1)),\n",
    "    ('MinMaxScaler', MinMaxScaler()),\n",
    "    ('LogisticRegression', LogisticRegression(max_iter=1000, dual=False, tol=0.1, fit_intercept=True, intercept_scaling=0.5, multi_class='deprecated', warm_start=False))\n",
    "])\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\model_selection\\_validation.py:528: FitFailedWarning: \n",
      "50 fits failed out of a total of 90.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\model_selection\\_validation.py\", line 866, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 1389, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\pipeline.py\", line 660, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 1382, in wrapper\n",
      "    estimator._validate_params()\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 436, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n",
      "        self._parameter_constraints,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "        self.get_params(deep=False),\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "        caller_name=self.__class__.__name__,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "    )\n",
      "    ^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\utils\\_param_validation.py\", line 98, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'solver' parameter of LogisticRegression must be a str among {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}. Got 'rbf' instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "2 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\model_selection\\_validation.py\", line 866, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 1389, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\pipeline.py\", line 660, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 1382, in wrapper\n",
      "    estimator._validate_params()\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 436, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n",
      "        self._parameter_constraints,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "        self.get_params(deep=False),\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "        caller_name=self.__class__.__name__,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "    )\n",
      "    ^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\utils\\_param_validation.py\", line 98, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'solver' parameter of LogisticRegression must be a str among {'sag', 'newton-cholesky', 'saga', 'lbfgs', 'newton-cg', 'liblinear'}. Got 'rbf' instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "3 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\model_selection\\_validation.py\", line 866, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 1389, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\pipeline.py\", line 660, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 1382, in wrapper\n",
      "    estimator._validate_params()\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 436, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n",
      "        self._parameter_constraints,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "        self.get_params(deep=False),\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "        caller_name=self.__class__.__name__,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "    )\n",
      "    ^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\utils\\_param_validation.py\", line 98, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'solver' parameter of LogisticRegression must be a str among {'newton-cholesky', 'lbfgs', 'saga', 'liblinear', 'newton-cg', 'sag'}. Got 'rbf' instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "2 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\model_selection\\_validation.py\", line 866, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 1389, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\pipeline.py\", line 660, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 1382, in wrapper\n",
      "    estimator._validate_params()\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 436, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n",
      "        self._parameter_constraints,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "        self.get_params(deep=False),\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "        caller_name=self.__class__.__name__,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "    )\n",
      "    ^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\utils\\_param_validation.py\", line 98, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'solver' parameter of LogisticRegression must be a str among {'lbfgs', 'newton-cg', 'newton-cholesky', 'liblinear', 'sag', 'saga'}. Got 'rbf' instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "3 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\model_selection\\_validation.py\", line 866, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 1389, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\pipeline.py\", line 660, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 1382, in wrapper\n",
      "    estimator._validate_params()\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 436, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n",
      "        self._parameter_constraints,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "        self.get_params(deep=False),\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "        caller_name=self.__class__.__name__,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "    )\n",
      "    ^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\utils\\_param_validation.py\", line 98, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'solver' parameter of LogisticRegression must be a str among {'liblinear', 'sag', 'newton-cholesky', 'newton-cg', 'saga', 'lbfgs'}. Got 'rbf' instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "3 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\model_selection\\_validation.py\", line 866, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 1389, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\pipeline.py\", line 660, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 1382, in wrapper\n",
      "    estimator._validate_params()\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 436, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n",
      "        self._parameter_constraints,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "        self.get_params(deep=False),\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "        caller_name=self.__class__.__name__,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "    )\n",
      "    ^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\utils\\_param_validation.py\", line 98, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'solver' parameter of LogisticRegression must be a str among {'saga', 'liblinear', 'newton-cholesky', 'newton-cg', 'sag', 'lbfgs'}. Got 'rbf' instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "3 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\model_selection\\_validation.py\", line 866, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 1389, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\pipeline.py\", line 660, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 1382, in wrapper\n",
      "    estimator._validate_params()\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 436, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n",
      "        self._parameter_constraints,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "        self.get_params(deep=False),\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "        caller_name=self.__class__.__name__,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "    )\n",
      "    ^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\utils\\_param_validation.py\", line 98, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'solver' parameter of LogisticRegression must be a str among {'sag', 'newton-cg', 'lbfgs', 'saga', 'newton-cholesky', 'liblinear'}. Got 'rbf' instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "2 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\model_selection\\_validation.py\", line 866, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 1389, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\pipeline.py\", line 660, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 1382, in wrapper\n",
      "    estimator._validate_params()\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 436, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n",
      "        self._parameter_constraints,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "        self.get_params(deep=False),\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "        caller_name=self.__class__.__name__,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "    )\n",
      "    ^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\utils\\_param_validation.py\", line 98, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'solver' parameter of LogisticRegression must be a str among {'sag', 'saga', 'newton-cholesky', 'liblinear', 'newton-cg', 'lbfgs'}. Got 'rbf' instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "2 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\model_selection\\_validation.py\", line 866, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 1389, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\pipeline.py\", line 660, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 1382, in wrapper\n",
      "    estimator._validate_params()\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 436, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n",
      "        self._parameter_constraints,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "        self.get_params(deep=False),\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "        caller_name=self.__class__.__name__,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "    )\n",
      "    ^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\utils\\_param_validation.py\", line 98, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'solver' parameter of LogisticRegression must be a str among {'newton-cg', 'sag', 'liblinear', 'newton-cholesky', 'saga', 'lbfgs'}. Got 'rbf' instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\model_selection\\_validation.py\", line 866, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 1389, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\pipeline.py\", line 660, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 1382, in wrapper\n",
      "    estimator._validate_params()\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 436, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n",
      "        self._parameter_constraints,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "        self.get_params(deep=False),\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "        caller_name=self.__class__.__name__,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "    )\n",
      "    ^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\utils\\_param_validation.py\", line 98, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'solver' parameter of LogisticRegression must be a str among {'liblinear', 'saga', 'sag', 'lbfgs', 'newton-cg', 'newton-cholesky'}. Got 'rbf' instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "2 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\model_selection\\_validation.py\", line 866, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 1389, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\pipeline.py\", line 660, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 1382, in wrapper\n",
      "    estimator._validate_params()\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 436, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n",
      "        self._parameter_constraints,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "        self.get_params(deep=False),\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "        caller_name=self.__class__.__name__,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "    )\n",
      "    ^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\utils\\_param_validation.py\", line 98, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'solver' parameter of LogisticRegression must be a str among {'sag', 'newton-cholesky', 'saga', 'newton-cg', 'liblinear', 'lbfgs'}. Got 'rbf' instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "2 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\model_selection\\_validation.py\", line 866, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 1389, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\pipeline.py\", line 660, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 1382, in wrapper\n",
      "    estimator._validate_params()\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 436, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n",
      "        self._parameter_constraints,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "        self.get_params(deep=False),\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "        caller_name=self.__class__.__name__,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "    )\n",
      "    ^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\utils\\_param_validation.py\", line 98, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'solver' parameter of LogisticRegression must be a str among {'sag', 'newton-cg', 'liblinear', 'saga', 'lbfgs', 'newton-cholesky'}. Got 'rbf' instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "2 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\model_selection\\_validation.py\", line 866, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 1389, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\pipeline.py\", line 660, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 1382, in wrapper\n",
      "    estimator._validate_params()\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 436, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n",
      "        self._parameter_constraints,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "        self.get_params(deep=False),\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "        caller_name=self.__class__.__name__,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "    )\n",
      "    ^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\utils\\_param_validation.py\", line 98, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'solver' parameter of LogisticRegression must be a str among {'newton-cg', 'sag', 'newton-cholesky', 'lbfgs', 'liblinear', 'saga'}. Got 'rbf' instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "10 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\model_selection\\_validation.py\", line 866, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 1389, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\pipeline.py\", line 660, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 1389, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\linear_model\\_logistic.py\", line 1193, in fit\n",
      "    solver = _check_solver(self.solver, self.penalty, self.dual)\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\linear_model\\_logistic.py\", line 71, in _check_solver\n",
      "    raise ValueError(\n",
      "        f\"Only 'saga' solver supports elasticnet penalty, got solver={solver}.\"\n",
      "    )\n",
      "ValueError: Only 'saga' solver supports elasticnet penalty, got solver=liblinear.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "10 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\model_selection\\_validation.py\", line 866, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 1389, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\pipeline.py\", line 660, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 1389, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\linear_model\\_logistic.py\", line 1203, in fit\n",
      "    raise ValueError(\"l1_ratio must be specified when penalty is elasticnet.\")\n",
      "ValueError: l1_ratio must be specified when penalty is elasticnet.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\model_selection\\_validation.py\", line 866, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 1389, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\pipeline.py\", line 660, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 1382, in wrapper\n",
      "    estimator._validate_params()\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 436, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n",
      "        self._parameter_constraints,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "        self.get_params(deep=False),\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "        caller_name=self.__class__.__name__,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "    )\n",
      "    ^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\utils\\_param_validation.py\", line 98, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'solver' parameter of LogisticRegression must be a str among {'lbfgs', 'newton-cholesky', 'newton-cg', 'sag', 'saga', 'liblinear'}. Got 'rbf' instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\model_selection\\_validation.py\", line 866, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 1389, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\pipeline.py\", line 660, in fit\n",
      "    self._final_estimator.fit(Xt, y, **last_step_params[\"fit\"])\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 1382, in wrapper\n",
      "    estimator._validate_params()\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\base.py\", line 436, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n",
      "        self._parameter_constraints,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "        self.get_params(deep=False),\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "        caller_name=self.__class__.__name__,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "    )\n",
      "    ^\n",
      "  File \"c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\utils\\_param_validation.py\", line 98, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "    ...<2 lines>...\n",
      "    )\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'solver' parameter of LogisticRegression must be a str among {'newton-cholesky', 'saga', 'liblinear', 'lbfgs', 'newton-cg', 'sag'}. Got 'rbf' instead.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "c:\\Users\\user\\Documents\\20204-2-LAB-02-prediccion-del-default-usando-logreg-lgallego06\\.venv\\Lib\\site-packages\\scikit_learn-1.6.0-py3.13-win-amd64.egg\\sklearn\\model_selection\\_search.py:1107: UserWarning: One or more of the test scores are non-finite: [0.72163439 0.71809819        nan 0.72596185 0.70561715        nan\n",
      "        nan        nan        nan]\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Mejores parámetros: {'LogisticRegression__C': 1, 'LogisticRegression__penalty': 'l2', 'LogisticRegression__solver': 'liblinear'}\n",
      "Mejor puntuación: 0.7259618503835443\n"
     ]
    }
   ],
   "source": [
    "\n",
    "from sklearn.model_selection import GridSearchCV, RandomizedSearchCV\n",
    "from sklearn.metrics import make_scorer, balanced_accuracy_score\n",
    "from sklearn.compose import ColumnTransformer\n",
    "import scipy.stats as stats\n",
    "\n",
    "np.random.seed(456)\n",
    "# Definir los hiperparámetros a optimizar para LogisticRegression\n",
    "# Definir las distribuciones de hiperparámetros\n",
    "param_distributions = {\n",
    "    'LogisticRegression__C':[1],\n",
    "    'LogisticRegression__penalty': ['l1','l2', 'elasticnet'],\n",
    "    'LogisticRegression__solver': ['liblinear', 'saga', 'rbf']\n",
    "}\n",
    "# Configurar la métrica de evaluación\n",
    "scorer = make_scorer(balanced_accuracy_score)\n",
    "\n",
    "# Modelo con GridSearchCV\n",
    "model = GridSearchCV(\n",
    "    estimator=pipeline,\n",
    "    param_grid=param_distributions,  # Cambiar `param_distributions` a `param_grid`\n",
    "    cv=10,\n",
    "    scoring='precision',\n",
    "    n_jobs=-1\n",
    ")\n",
    "\n",
    "# Entrenar el modelo\n",
    "model.fit(x_train, y_train)\n",
    "\n",
    "# Mejor modelo y mejores hiperparámetros\n",
    "print(\"Mejores parámetros:\", model.best_params_)\n",
    "print(\"Mejor puntuación:\", model.best_score_)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'LogisticRegression__C': 1, 'LogisticRegression__penalty': 'l2', 'LogisticRegression__solver': 'liblinear'}\n"
     ]
    }
   ],
   "source": [
    "print(model.best_params_)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pickle\n",
    "import os\n",
    "\n",
    "models_dir = '../files/models'\n",
    "os.makedirs(models_dir, exist_ok=True)\n",
    "\n",
    "with open(\"../files/models/model.pkl\",\"wb\") as file:\n",
    "    pickle.dump(model,file)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "import json\n",
    "from sklearn.metrics import precision_score, recall_score, f1_score, balanced_accuracy_score\n",
    "\n",
    "def calculate_and_save_metrics(model, X_train, X_test, y_train, y_test):\n",
    "    # Hacer predicciones\n",
    "    y_train_pred = model.predict(X_train)\n",
    "    y_test_pred = model.predict(X_test)\n",
    "\n",
    "    # Calcular métricas para el conjunto de entrenamiento\n",
    "    metrics_train = {\n",
    "        'type': 'metrics',\n",
    "        'dataset': 'train',\n",
    "        'precision': precision_score(y_train, y_train_pred, zero_division=0),\n",
    "        'balanced_accuracy': balanced_accuracy_score(y_train, y_train_pred),\n",
    "        'recall': recall_score(y_train, y_train_pred, zero_division=0),\n",
    "        'f1_score': f1_score(y_train, y_train_pred, zero_division=0)\n",
    "    }\n",
    "\n",
    "    # Calcular métricas para el conjunto de prueba\n",
    "    metrics_test = {\n",
    "        'type': 'metrics',\n",
    "        'dataset': 'test',\n",
    "        'precision': precision_score(y_test, y_test_pred, zero_division=0),\n",
    "        'balanced_accuracy': balanced_accuracy_score(y_test, y_test_pred),\n",
    "        'recall': recall_score(y_test, y_test_pred, zero_division=0),\n",
    "        'f1_score': f1_score(y_test, y_test_pred, zero_division=0)\n",
    "    }\n",
    "\n",
    "    # Crear carpeta si no existe\n",
    "    output_dir = '../files/output'\n",
    "    os.makedirs(output_dir, exist_ok=True)\n",
    "\n",
    "    # Guardar las métricas en un archivo JSON\n",
    "    output_path = os.path.join(output_dir, 'metrics.json')\n",
    "    with open(output_path, 'w') as f:  # Usar 'w' para comenzar con un archivo limpio\n",
    "        f.write(json.dumps(metrics_train) + '\\n')\n",
    "        f.write(json.dumps(metrics_test) + '\\n')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.metrics import confusion_matrix\n",
    "# Función para calcular las matrices de confusión y guardarlas\n",
    "def calculate_and_save_confusion_matrices(model, X_train, X_test, y_train, y_test):\n",
    "    # Hacer predicciones\n",
    "    y_train_pred = model.predict(X_train)\n",
    "    y_test_pred = model.predict(X_test)\n",
    "\n",
    "    # Calcular matrices de confusión\n",
    "    cm_train = confusion_matrix(y_train, y_train_pred)\n",
    "    cm_test = confusion_matrix(y_test, y_test_pred)\n",
    "\n",
    "    # Convertir las matrices de confusión en formato JSON\n",
    "    def format_confusion_matrix(cm, dataset_type):\n",
    "        return {\n",
    "            'type': 'cm_matrix',\n",
    "            'dataset': dataset_type,\n",
    "            'true_0': {\n",
    "                'predicted_0': int(cm[0, 0]),\n",
    "                'predicted_1': int(cm[0, 1])\n",
    "            },\n",
    "            'true_1': {\n",
    "                'predicted_0': int(cm[1, 0]),\n",
    "                'predicted_1': int(cm[1, 1])\n",
    "            }\n",
    "        }\n",
    "\n",
    "    metrics = [\n",
    "        format_confusion_matrix(cm_train, 'train'),\n",
    "        format_confusion_matrix(cm_test, 'test')\n",
    "    ]\n",
    "\n",
    "    # Guardar las matrices de confusión en el mismo archivo JSON\n",
    "    output_path = '../files/output/metrics.json'\n",
    "    with open(output_path, 'a') as f:  # Usar 'a' para agregar después de las métricas\n",
    "        for metric in metrics:\n",
    "            f.write(json.dumps(metric) + '\\n')\n",
    "\n",
    "# Función principal para ejecutar todo\n",
    "def main(model, X_train, X_test, y_train, y_test):\n",
    "    # Crear el directorio de salida si no existe\n",
    "    import os\n",
    "    os.makedirs('../files/output', exist_ok=True)\n",
    "\n",
    "    # Calcular y guardar las métricas\n",
    "    calculate_and_save_metrics(model, X_train, X_test, y_train, y_test)\n",
    "\n",
    "    # Calcular y guardar las matrices de confusión\n",
    "    calculate_and_save_confusion_matrices(model, X_train, X_test, y_train, y_test)\n",
    "\n",
    "# Ejemplo de uso:\n",
    "main(model, x_train, x_test, y_train, y_test)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
